In [1]:
import numpy as np

In [3]:
arr1 = np.array([]) #create an empty array
arr1

array([], dtype=float64)

In [4]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [5]:
a = np.array(my_list)

In [6]:
a

array([1, 2, 3, 4, 5])

In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
a.ndim #number of dimensions in the array

1

In [11]:
a.size #size of an array is the no of items

5

In [12]:
a.shape #shape array

(5,)

### Array can be of n Dimensions

In [13]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [15]:
b = np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
b.ndim

2

In [18]:
b.size

12

In [19]:
b.shape #row,colmn

(3, 4)

In [20]:
b.dtype

dtype('int64')

In [26]:
arr1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr1.shape

(2, 2, 3)

In [28]:
arr1.ndim

3

In [29]:
arr1.size

12

In [30]:
arr1.dtype

dtype('int64')

## Built In Methods

In [32]:
arr2 = arr1.reshape((1,3,4))
arr2.shape

(1, 3, 4)

In [33]:
arr2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.arange(100,2,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [37]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

###  Zeros and ones

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.ones(3)

array([1., 1., 1.])

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## linspace
Return evenly spaced numbers over a specified interval

In [65]:
np.linspace(1,15) #default 50 observation

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [74]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [69]:
np.linspace(0,25,retstep = True)

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [71]:
np.linspace(0,200,11)

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.])

## eye
creates an identity matrix

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# use of copy function

In [23]:
import numpy as np
arr3 =np.array([1,2,3,4,5,6,7,8,9])
arr4 =np.array([10,11,12,13,15,16,17])

In [24]:
arr4 = arr3
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr4[5] = 30 
arr4

array([ 1,  2,  3,  4,  5, 30,  7,  8,  9])

In [26]:
arr3

array([ 1,  2,  3,  4,  5, 30,  7,  8,  9])

In [27]:
arr5 = arr3.copy()

In [29]:
arr5[1:]=100
arr5

array([  1, 100, 100, 100, 100, 100, 100, 100, 100])

# Random 

In [30]:
np.random.rand()

0.795493603113648

In [32]:
np.random.rand(10)

array([0.25010505, 0.93763172, 0.57762872, 0.92092519, 0.05732417,
       0.40173182, 0.35978566, 0.18541144, 0.08628119, 0.72279997])

In [33]:
np.random.rand(10).reshape((2,5))

array([[0.8853104 , 0.97443361, 0.92451688, 0.04266126, 0.72005638],
       [0.08547066, 0.75649076, 0.10541863, 0.29469579, 0.21636014]])

In [37]:
arr1 = np.random.randn()
arr1

1.2065934749594953

In [38]:
arr1 = np.random.randn(50)
arr1

array([ 0.56102558, -1.78493546, -0.89574351,  0.81459846, -0.66322345,
        1.26147216,  1.26852481,  0.41809975,  0.59188209, -0.7458973 ,
       -0.3605119 ,  0.32795515, -0.90615617, -2.15105275, -1.31814774,
        1.48331211,  1.81614537, -0.11676513,  0.42691603,  0.35693083,
        1.48903973, -1.44833903,  1.31460616,  0.50385347,  0.94774438,
        0.91676092, -0.35096298, -1.37361229, -1.73426809,  1.96775179,
        0.68733341, -0.43001904, -1.13491234,  0.8340104 ,  0.87470651,
        0.07809115,  0.75452207,  0.39139778, -0.36243881, -0.94715232,
       -0.09468732, -0.23140918,  1.41487416,  0.64841594, -0.64029931,
       -0.81230864, -0.49985683,  1.09491921, -1.17137583,  1.5788248 ])

## Randint

In [42]:
np.random.randint(1,100)

28

In [43]:
np.random.randint(1,100,10)

array([84, 86, 84, 47, 39, 91, 42, 43, 88, 89])

In [44]:
np.random.randint(40,60,50)

array([53, 56, 49, 57, 44, 42, 51, 45, 58, 52, 48, 48, 51, 55, 50, 45, 40,
       56, 54, 42, 40, 46, 54, 44, 51, 50, 59, 48, 57, 54, 47, 42, 57, 48,
       55, 59, 40, 47, 41, 43, 51, 54, 59, 53, 42, 43, 48, 48, 45, 56])