In [1]:
import pandas as pd

In [2]:
data = {
    'Name' : ['Aditya','James','Buck'],
    'Age' : [22,23,25],
    'city' : ['New York','LA','Chicago']
}
df = pd.DataFrame(data)
print(df)

     Name  Age      city
0  Aditya   22  New York
1   James   23        LA
2    Buck   25   Chicago


In [3]:
import numpy as np

array = np.array([10,20,30,40,50,60])
mean = np.mean(array)
std_dev = np.std(array)
print(f"Mean: {mean},Standard Deviation: {std_dev}")

Mean: 35.0,Standard Deviation: 17.07825127659933


In [4]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})
print(df['B'])


0    4
1    5
2    6
Name: B, dtype: int64


In [5]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Anna', 'Bill', 'Catherine'],
    'Score': [85, 92, 78]
})
filtered_df = df[df['Score'] > 80]
print(filtered_df)


   Name  Score
0  Anna     85
1  Bill     92


In [6]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2
print(result)


[5 7 9]


In [7]:
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, None],
    'B': [4, None, 6],
    'C': [7, 8, 9]
})
df_filled = df.fillna(0)
print(df_filled)


     A    B  C
0  1.0  4.0  7
1  2.0  0.0  8
2  0.0  6.0  9


In [8]:
import numpy as np

sequence = np.arange(0, 10, 2)
print(sequence)


[0 2 4 6 8]


In [9]:
import pandas as pd

df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B'],
    'Value': [10, 20, 15, 25]
})
grouped_df = df.groupby('Category').mean()
print(grouped_df)


          Value
Category       
A          12.5
B          22.5


In [10]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((2, 3))
print(reshaped_array)


[[1 2 3]
 [4 5 6]]


In [11]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['John', 'Paul', 'George']
})
df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Age': [28, 32, 35]
})
merged_df = pd.merge(df1, df2, on='ID')
print(merged_df)


   ID    Name  Age
0   1    John   28
1   2    Paul   32
2   3  George   35
